spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath*:mysqldb/schema.sql
    data: classpath*:mysqldb/data.sql
    initialization-mode: always
security:
  basic:
    enabled: false
