
server:
  port: 8001

spring:
  application:
    name: veterinarian_service
  datasource:
    schema: classpath*:hsqldb/schema.sql
    data: classpath*:hsqldb/data1.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
