spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath*:mysqldb/schema.sql
    data: classpath*:mysqldb/data.sql
    initialization-mode: always
   autoconfigure:
     exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
     exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
